version: '3'

services:
        db:
                image: mariadb:latest
                hostname: mariadb
                ports:
                        - 3306:3306
                volumes:
                        - ./db/db_data:/var/lib/mysql
                        - ./db/schemas.d:/docker-entrypoint-initdb.d
                environment:
                        MYSQL_ROOT_PASSWORD: phiopolis
                        MYSQL_DATABASE: phiopolis_db
                        MYSQL_USER: phi
                        MYSQL_PASSWORD: 12345678
